{
  src
  {
        utility.m
        global_variables.m
        Jordan.m
        small.m
        Lie
        {
             structure.m
             normalizer.m
             conjugacy.m
        }
        Assoc
        {
             structure.m
             cyclic.m
             normalizer.m
             conjugacy.m
        }
        Star
        {
             structure.m
             normalizer.m
             conjugacy.m
        }
  }
}
